
#include "Precomp.h"
#include "MSIDialog.h"
#include "Base64/Base64.h"

#ifdef WIN32

// These are all garbage - visually obsolete by a couple of decades at this point. Remove them from the dialogs or find some new ones?
static const char* binary_completi = "AAABAAIAICAQAAAAAADoAgAAJgAAACAgAAAAAAAAqAgAAA4DAAAoAAAAIAAAAEAAAAABAAQAAAAAAIACAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIgAAAAAAAAAAAAAAAAACId7u6AAAAAAAAAAAAAAAI9/d7uqoAAAAAAAAAAAAAh49/u6qncAAAAAAAAAAAAIh493uqd3AAAAAAAAAAAAiHh497p3fuAAAAAAAAAAAIeHh4AKfu7gAAAAAAAAAACIeHgP8O7ncAAAAAAAAAAAh3fuD/CHh4AAAAAAAAAAAIfueuAIeHhwd3d3cAiIiICO567r/4eHgAAAB3gI+f+ACHru6/f4eAiIiId4CJmfgAiu7rt/f4cP////+AmfmYAAjuu7d/fwiIiIiHgI//mQAAiLu3dwAAAAAAAHCIiImQAACIiIh3d3d3d3gAAAAAkAAACP////////94AIiIiAAAAAj0RERERERPeACPn/gAAAAI9Od2ZmzMT3gAiZn4AAAACPT+d2ZmzE94AJn5mAAAAAj07+d2ZmxPeACP/5kAAAAI9P7+d2ZmT3gAiIiJkAAACPTv7+d2Zk94AAAAAJAAAAj0fv7+d2ZPeACIiIgAAAAI9Hfv7+d2T3gAj5/4AAAACPR3fv7+d094AImZ+AAAAAj0RERERERPeACZ+ZgAAAAI/////////3gAj/+ZAAAAAIiIiIiIiIiIAIiIiZAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAA///////wP///wA///4AH//8AA///AAP//gAB//4AAf/+AAH//gAAA/4AAAECAAAAAwAAAAMAAAADgAAAA8AAAAHwAAH9+AABA/gAAQP4AAED+AABA/gAAQP4AAEB+AAB/fgAAQP4AAED+AABA/gAAQP4AAED/AADAf////3///8oAAAAIAAAAEAAAAABAAgAAAAAAIAEAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmANTw/wCx4v8AjtT/AGvG/wBIuP8AJar/AACq/wAAktwAAHq5AABilgAASnMAADJQANTj/wCxx/8Ajqv/AGuP/wBIc/8AJVf/AABV/wAASdwAAD25AAAxlgAAJXMAABlQANTU/wCxsf8Ajo7/AGtr/wBISP8AJSX/AAAA/gAAANwAAAC5AAAAlgAAAHMAAABQAOPU/wDHsf8Aq47/AI9r/wBzSP8AVyX/AFUA/wBJANwAPQC5ADEAlgAlAHMAGQBQAPDU/wDisf8A1I7/AMZr/wC4SP8AqiX/AKoA/wCSANwAegC5AGIAlgBKAHMAMgBQAP/U/wD/sf8A/47/AP9r/wD/SP8A/yX/AP4A/gDcANwAuQC5AJYAlgBzAHMAUABQAP/U8AD/seIA/47UAP9rxgD/SLgA/yWqAP8AqgDcAJIAuQB6AJYAYgBzAEoAUAAyAP/U4wD/sccA/46rAP9rjwD/SHMA/yVXAP8AVQDcAEkAuQA9AJYAMQBzACUAUAAZAP/U1AD/sbEA/46OAP9rawD/SEgA/yUlAP4AAADcAAAAuQAAAJYAAABzAAAAUAAAAP/j1AD/x7EA/6uOAP+PawD/c0gA/1clAP9VAADcSQAAuT0AAJYxAABzJQAAUBkAAP/w1AD/4rEA/9SOAP/GawD/uEgA/6olAP+qAADckgAAuXoAAJZiAABzSgAAUDIAAP//1AD//7EA//+OAP//awD//0gA//8lAP7+AADc3AAAubkAAJaWAABzcwAAUFAAAPD/1ADi/7EA1P+OAMb/awC4/0gAqv8lAKr/AACS3AAAerkAAGKWAABKcwAAMlAAAOP/1ADH/7EAq/+OAI//awBz/0gAV/8lAFX/AABJ3AAAPbkAADGWAAAlcwAAGVAAANT/1ACx/7EAjv+OAGv/awBI/0gAJf8lAAD+AAAA3AAAALkAAACWAAAAcwAAAFAAANT/4wCx/8cAjv+rAGv/jwBI/3MAJf9XAAD/VQAA3EkAALk9AACWMQAAcyUAAFAZANT/8ACx/+IAjv/UAGv/xgBI/7gAJf+qAAD/qgAA3JIAALl6AACWYgAAc0oAAFAyANT//wCx//8Ajv//AGv//wBI//8AJf//AAD+/gAA3NwAALm5AACWlgAAc3MAAFBQAPLy8gDm5uYA2traAM7OzgDCwsIAtra2AKqqqgCenp4AkpKSAIaGhgB6enoAbm5uAGJiYgBWVlYASkpKAD4+PgAyMjIAJiYmABoaGgAODg4A8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7+/v8vLyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7+/l5diylYny8gAAAAAAAAAAAAAAAAAAAAAAAAAAAO/m5uXl2LKViZec8gAAAAAAAAAAAAAAAAAAAAAAAADv5+bm5uXYlYmXnJyc8gAAAAAAAAAAAAAAAAAAAAAAAO3n5+bm5diJl5yc4+PyAAAAAAAAAAAAAAAAAAAAAADv5+fn5+bl5Zec4+Pj4+PyAAAAAAAAAAAAAAAAAAAAAO/l5+fn5+YAAOPj4+fn5/IAAAAAAAAAAAAAAAAAAAAA7+Xl5efnAP//AOvr6+fn8gAAAAAAAAAAAAAAAAAAAADv6enp6ekA//8A5OTr6+vyAAAAAAAAAAAAAAAAAAAAAO/j45yclZUAAOf3/+Tn5/Ln5+fn5+fnAADr6+vr6+sA7+OclZWJ6enN5/fm/+Tk8gAAAAAA5ufrAOv/+f//6wAA75WViemp2M3n5/fm//Lr6+vr6+vm5+sA6/kb+f/rAADvlYmJ6djYzc3n9/fm8ubm5ubm5ubn6wD5G/8b+esAAADviemp2M3Nzefn9/Lr6+vr6+vr6+frAOv///8b+QAAAADt7anYzc3N5/LyAAAAAAAAAAAAAOf16+vr6+sb+QAAAAAA6urq6u3t5ubm5ubm5ubm5ubrAAD////////5AAAAAAAA6///////////////////5usAAOvr6+vr6wAAAAAAAADr/wQEBAQEBAQEBAQEBP/m6wAA6//5///rAAAAAAAAAOv/BP6FhYmJiYl7e3sE/+brAADr+Rv5/+sAAAAAAAAA6/8EjpOFhYmJiYl7ewT/5usAAPkb/xv56wAAAAAAAADr/wSTjpOFhYmJiYl7BP/m6wAA6////xv5AAAAAAAAAOv/BI6TjpOFhYmJiYkE/+brAADr6+vr6xv5AAAAAAAA6/8Ek46TjpOFhYmJiQT/5usAAP////////kAAAAAAADr/wSFk46TjpOFhYmJBP/m6wAA6+vr6+vrAAAAAAAAAOv/BIWFk46TjpOFhYkE/+brAADr//n//+sAAAAAAAAA6/8EhYWFk46Tjv6FhQT/5usAAOv5G/n/6wAAAAAAAADr/wQEBAQEBAQEBAQEBP/m6wAA+Rv/G/nrAAAAAAAAAOv//////////////////+brAADr////G/kAAAAAAAAAAO3t7e3t7e3t7e3t7e3t7e0AAOvr6+vrG/kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////A////AD///gAf//wAD//8AA//+AAH//gAB//4AAf/+AAAD/gAAAQIAAAADAAAAAwAAAAOAAAADwAAAAfAAAQH4AAED+AABA/gAAQP4AAED+AABA/gAAQH4AAEB+AABA/gAAQP4AAED+AABA/gAAQP8AAMB/////f///w==";
static const char* binary_custicon = "AAABAAIAICAQAAAAAADoAgAAJgAAACAgAAAAAAAAqAgAAA4DAAAoAAAAIAAAAEAAAAABAAQAAAAAAIACAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIgAAAAAAAAAAAAAAAAACId7u6AAAAAAAAAAAAAAAI9/d7uqoAAAAAAAAAAAAAh49/u6qncAAAAAAAAAAAAIh493uqd3AAAAAAAAAAAAiHh497p3fuAAAAAAAAAAAIeHh4AKfu7gAAAAAAAAAACIeHgP8O7ncAAAAAAAAAAAh3fuD/CHh4AAAAAAAAAAAIfueuAIeHhwd3d3cAAAAACO567r/4eHgAAAB3gI//8ACHru6/f4eAiIiId4CP//AAiu7rt/f4cP////+Aj//wAAjuu7d/fwiIiIiHgI//8AAAiLu3dwAAAAAAAHCIiIAAAACIiIh3d3d3d3gAAAAAAAAACP////////94AAAAAAAAAAj0RERERERPeACP//AAAAAI9Od2ZmzMT3gAj//wAAAACPT+d2ZmzE94AI//8AAAAAj07+d2ZmxPeACP//AAAAAI9P7+d2ZmT3gAiIiAAAAACPTv7+d2Zk94AAAAAAAAAAj0fv7+d2ZPeACIiIgAAAAI9Hfv7+d2T3gAj5/4AAAACPR3fv7+d094AImZ+AAAAAj0RERERERPeACZ+ZgAAAAI/////////3gAj/+ZAAAAAIiIiIiIiIiIAIiIiZAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAA///////wP///wA///4AH//8AA///AAP//gAB//4AAf/+AAH//gAAA/4AAAECAAAAAwAAAAMAAAADgAAAA8AAAAPwAAH/+AABA/gAAQP4AAED+AABA/gAAQP4AAED+AAB//gAAQP4AAED+AABA/gAAQP4AAED/AADAf////3///8oAAAAIAAAAEAAAAABAAgAAAAAAIAEAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmANTw/wCx4v8AjtT/AGvG/wBIuP8AJar/AACq/wAAktwAAHq5AABilgAASnMAADJQANTj/wCxx/8Ajqv/AGuP/wBIc/8AJVf/AABV/wAASdwAAD25AAAxlgAAJXMAABlQANTU/wCxsf8Ajo7/AGtr/wBISP8AJSX/AAAA/gAAANwAAAC5AAAAlgAAAHMAAABQAOPU/wDHsf8Aq47/AI9r/wBzSP8AVyX/AFUA/wBJANwAPQC5ADEAlgAlAHMAGQBQAPDU/wDisf8A1I7/AMZr/wC4SP8AqiX/AKoA/wCSANwAegC5AGIAlgBKAHMAMgBQAP/U/wD/sf8A/47/AP9r/wD/SP8A/yX/AP4A/gDcANwAuQC5AJYAlgBzAHMAUABQAP/U8AD/seIA/47UAP9rxgD/SLgA/yWqAP8AqgDcAJIAuQB6AJYAYgBzAEoAUAAyAP/U4wD/sccA/46rAP9rjwD/SHMA/yVXAP8AVQDcAEkAuQA9AJYAMQBzACUAUAAZAP/U1AD/sbEA/46OAP9rawD/SEgA/yUlAP4AAADcAAAAuQAAAJYAAABzAAAAUAAAAP/j1AD/x7EA/6uOAP+PawD/c0gA/1clAP9VAADcSQAAuT0AAJYxAABzJQAAUBkAAP/w1AD/4rEA/9SOAP/GawD/uEgA/6olAP+qAADckgAAuXoAAJZiAABzSgAAUDIAAP//1AD//7EA//+OAP//awD//0gA//8lAP7+AADc3AAAubkAAJaWAABzcwAAUFAAAPD/1ADi/7EA1P+OAMb/awC4/0gAqv8lAKr/AACS3AAAerkAAGKWAABKcwAAMlAAAOP/1ADH/7EAq/+OAI//awBz/0gAV/8lAFX/AABJ3AAAPbkAADGWAAAlcwAAGVAAANT/1ACx/7EAjv+OAGv/awBI/0gAJf8lAAD+AAAA3AAAALkAAACWAAAAcwAAAFAAANT/4wCx/8cAjv+rAGv/jwBI/3MAJf9XAAD/VQAA3EkAALk9AACWMQAAcyUAAFAZANT/8ACx/+IAjv/UAGv/xgBI/7gAJf+qAAD/qgAA3JIAALl6AACWYgAAc0oAAFAyANT//wCx//8Ajv//AGv//wBI//8AJf//AAD+/gAA3NwAALm5AACWlgAAc3MAAFBQAPLy8gDm5uYA2traAM7OzgDCwsIAtra2AKqqqgCenp4AkpKSAIaGhgB6enoAbm5uAGJiYgBWVlYASkpKAD4+PgAyMjIAJiYmABoaGgAODg4A8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7+/v8vLyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7+/l5diylYny8gAAAAAAAAAAAAAAAAAAAAAAAAAAAO/m5uXl2LKViZec8gAAAAAAAAAAAAAAAAAAAAAAAADv5+bm5uXYlYmXnJyc8gAAAAAAAAAAAAAAAAAAAAAAAO3n5+bm5diJl5yc4+PyAAAAAAAAAAAAAAAAAAAAAADv5+fn5+bl5Zec4+Pj4+PyAAAAAAAAAAAAAAAAAAAAAO/l5+fn5+YAAOPj4+fn5/IAAAAAAAAAAAAAAAAAAAAA7+Xl5efnAP//AOvr6+fn8gAAAAAAAAAAAAAAAAAAAADv6enp6ekA//8A5OTr6+vyAAAAAAAAAAAAAAAAAAAAAO/j45yclZUAAOf3/+Tn5/Ln5+fn5+fnAADy8vLy8vIA7+OclZWJ6enN5/fm/+Tk8gAAAAAA5ufrAOn/////8gAA75WViemp2M3n5/fm//Lr6+vr6+vm5+sA6f/////yAADvlYmJ6djYzc3n9/fm8ubm5ubm5ubn6wDp//////IAAADviemp2M3Nzefn9/Lr6+vr6+vr6+frAOn/////8gAAAADt7anYzc3N5/LyAAAAAAAAAAAAAOf16enp6enyAAAAAAAA6urq6u3t5ubm5ubm5ubm5ubrAAAAAAAAAAAAAAAAAAAA6///////////////////5usAAPLy8vLy8gAAAAAAAADr/wQEBAQEBAQEBAQEBP/m6wAA6f/////yAAAAAAAAAOv/BP6FhYmJiYl7e3sE/+brAADp//////IAAAAAAAAA6/8EjpOFhYmJiYl7ewT/5usAAOn/////8gAAAAAAAADr/wSTjpOFhYmJiYl7BP/m6wAA6f/////yAAAAAAAAAOv/BI6TjpOFhYmJiYkE/+brAADp6enp6fIAAAAAAAAA6/8Ek46TjpOFhYmJiQT/5usAAAAAAAAAAAAAAAAAAADr/wSFk46TjpOFhYmJBP/m6wAA6enp6enpAAAAAAAAAOv/BIWFk46TjpOFhYkE/+brAADp//n//+kAAAAAAAAA6/8EhYWFk46Tjv6FhQT/5usAAOn5G/n/6QAAAAAAAADr/wQEBAQEBAQEBAQEBP/m6wAAGxv/G/npAAAAAAAAAOv//////////////////+brAADp////G/kAAAAAAAAAAO3t7e3t7e3t7e3t7e3t7e0AAOnp6enpG/kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////A////AD///gAf//wAD//8AA//+AAH//gAB//4AAf/+AAAD/gAAAQIAAAADAAAAAwAAAAOAAAADwAAAA/AAAf/4AAED+AABA/gAAQP4AAED+AABA/gAAQP4AAH/+AABA/gAAQP4AAED+AABA/gAAQP8AAMB/////f///w==";
static const char* binary_exclamic = "AAABAAEAICAQAAAAAADoAgAAFgAAACgAAAAgAAAAQAAAAAEABAAAAAAAgAIAAAAAAAAAAAAAAAAAAAAAAADAwMAAgICAAACAgAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzMxERERERERERERERETMzMyMzMzMzMzMzMzMzMzETMzJEREREREREREREREQDETMkREREREREREREREREQDEzJERERERERAREREREREQxMyREREREREMzREREREREMTMkREREREQDMwREREREQDEzMkREREREQzNEREREREMRMzJEREREREQEREREREQDEzMzJEREREREREREREREMRMzMyRERERERDREREREQDEzMzMyREREREAwREREREMRMzMzMkRERERCMkREREQDEzMzMzMkREREQzNEREREMRMzMzMzJERERAMzBEREQDEzMzMzMzJEREQjMyREREMRMzMzMzMyREREMzM0REQDEzMzMzMzMyRERDMzNEREMRMzMzMzMzMkREQzMzREQDEzMzMzMzMzMkREMzM0REMRMzMzMzMzMzJERDMzNEQDEzMzMzMzMzMzJEQDMwREMRMzMzMzMzMzMyREREREQDEzMzMzMzMzMzMyREREREMRMzMzMzMzMzMzMkREREQDEzMzMzMzMzMzMzMkREREMRMzMzMzMzMzMzMzJEREQDEzMzMzMzMzMzMzMzJEREMRMzMzMzMzMzMzMzMyREQDEzMzMzMzMzMzMzMzMyRAMTMzMzMzMzMzMzMzMzMyIjMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzP4AAAH4AAAA8AAAAGAAAABgAAAAYAAAAGAAAABwAAAAcAAAAPgAAAD4AAAB/AAAAfwAAAP+AAAD/gAAB/8AAAf/AAAP/4AAD/+AAB//wAAf/8AAP//gAD//4AB///AAf//wAP//+AD///gB///8Af///AP///4H////H///////w==";
static const char* binary_info = "AAABAAIAICAQAAAAAADoAgAAJgAAABAQEAAAAAAAKAEAAA4DAAAoAAAAIAAAAEAAAAABAAQAAAAAAIACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAICAgADAwMAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAdwAAAAAAAAAAAAAAAAAAB3cAAAAAAAAAAAAAAAAAAAB3AAAAAAAAAAAAAAAAAADwdwAAAAAAAAAAAAAAAAAP8HcAAAAAAAAAAAAAAABw//B3AAAAAAAAAAAAAAd3cP/wd3dwAAAAAAAAAAd3AAj/8Hd3d3AAAAAAAABwAI////gAB3d3AAAAAAAACP///////4AHd3AAAAAACP//////////gHd3AAAAAP////////////8Hd3AAAA//////////////8Hd3AAf/////zMzMzM////8HdwB4///////MzM//////gHdwf///////zMzP//////B3d4///////8zMz//////4B3f////////MzM///////wd3////////zMzP//////8Hd////////8zMz///////B3f////////MzM///////wd3///////MzMzP//////8HB4/////////////////4BwB/////////////////8HAAeP/////4zMyP/////4AAAAf//////MzMz/////8AAAAAf/////zMzM/////wAAAAAAf////4zMyP////AAAAAAAAeP//////////hwAAAAAAAAd4////////h3AAAAAAAAAAB3eP///4d3AAAAAAAAAAAAAAd3d3dwAAAAAAAA///n////x////4f///8H///+B///+Af//8AA//8AAD/+AAAf/AAAD/gAAAfwAAAD4AAAAcAAAAGAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAGAAAADgAAAB8AAAA/gAAAf8AAAP/gAAH/8AAD//wAD///gH/8oAAAAEAAAACAAAAABAAQAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAICAgADAwMAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAABwAAAAAABw8HAAAAAAcA/wcAAAAAAI//B3AAAACP//8AdwAAeP////gHcAf///////BwB///zMz/8Hd////8z///B3////zP//8Hf///zM///wd/////////AAf///zP//AAB4//+I//8AAAd4////dwAAAAd3d3cAAA/48AAP4PAAD4DwAA8AcAAOADAADAAQAAgAEAAIAAAAAAAAAAAAAAAAAAAAAAAQAAgAMAAIADAADABwAA8B8AAA==";
static const char* binary_insticon = "AAABAAIAICAQAAAAAADoAgAAJgAAACAgAAAAAAAAqAgAAA4DAAAoAAAAIAAAAEAAAAABAAQAAAAAAIACAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAIiAAAAAAAAAAAAAAAAAAIh3u7oAAAAAAAAIf38AAAj393u6qgAAAAAACPf3CACHj3+7qqdwAAAAAAh/fweAiHj3e6p3cAAAAAAI9/cIeIeHj3und+4AAAAACH9/B4h4eHgAp+7uAAAAAAj39wh4h4eA/w7udwAAAAAIf38HiHd+4P8IeHgAAAAACPf3CHh+564Ah4eHAAAAAAj//weI7nruv/h4eAAAAAAI//8IeIeu7r9/h4AAAAAACP//B4eK7uu39/hwd3dwAAj//wd3eO67t39/AAAHeAAI//8Hd3CIu7d3AIiIh3gACP//B3dw/4iIiP/////4AAiIiAd3cIiIiIiIiIiIeAAIiIgHd3AAAAAAAAAAAAcAj///gHdwh3d3d3d3d3eACIiIiIgHcI/////////3gAAAAIiIgHCPRERERERE94AAAAAIiIgAj053ZmbMxPeAAAAAAI//8I9P53ZmbMT3gAAAAAAIiIgPTv53ZmbE94AAAAAAAAAAj0/v53ZmZPeAAAAAAAAAAI9O/v53ZmT3gAAAAAAAAACPR+/v53Zk94AAAAAAAAAAj0d+/v53ZPeAAAAAAAAAAI9Hd+/v53T3gAAAAAAAAACPRERERERE94AAAAAAAAAAj/////////eAAAAAAAAAAAiIiIiIiIiIgA//4H/8D4Af/AcAD/wCAAf8AAAH/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAADwAAAAcAAAADAAAAAwAAAAMAAAADAAAAAgAAAAQAAAAH4AAAB/AAAAf4AAAH/AAAB//gAAf/4AAH/+AAB//gAAf/4AAH/+AAB//gAAf/8AAMoAAAAIAAAAEAAAAABAAgAAAAAAIAEAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmANTw/wCx4v8AjtT/AGvG/wBIuP8AJar/AACq/wAAktwAAHq5AABilgAASnMAADJQANTj/wCxx/8Ajqv/AGuP/wBIc/8AJVf/AABV/wAASdwAAD25AAAxlgAAJXMAABlQANTU/wCxsf8Ajo7/AGtr/wBISP8AJSX/AAAA/gAAANwAAAC5AAAAlgAAAHMAAABQAOPU/wDHsf8Aq47/AI9r/wBzSP8AVyX/AFUA/wBJANwAPQC5ADEAlgAlAHMAGQBQAPDU/wDisf8A1I7/AMZr/wC4SP8AqiX/AKoA/wCSANwAegC5AGIAlgBKAHMAMgBQAP/U/wD/sf8A/47/AP9r/wD/SP8A/yX/AP4A/gDcANwAuQC5AJYAlgBzAHMAUABQAP/U8AD/seIA/47UAP9rxgD/SLgA/yWqAP8AqgDcAJIAuQB6AJYAYgBzAEoAUAAyAP/U4wD/sccA/46rAP9rjwD/SHMA/yVXAP8AVQDcAEkAuQA9AJYAMQBzACUAUAAZAP/U1AD/sbEA/46OAP9rawD/SEgA/yUlAP4AAADcAAAAuQAAAJYAAABzAAAAUAAAAP/j1AD/x7EA/6uOAP+PawD/c0gA/1clAP9VAADcSQAAuT0AAJYxAABzJQAAUBkAAP/w1AD/4rEA/9SOAP/GawD/uEgA/6olAP+qAADckgAAuXoAAJZiAABzSgAAUDIAAP//1AD//7EA//+OAP//awD//0gA//8lAP7+AADc3AAAubkAAJaWAABzcwAAUFAAAPD/1ADi/7EA1P+OAMb/awC4/0gAqv8lAKr/AACS3AAAerkAAGKWAABKcwAAMlAAAOP/1ADH/7EAq/+OAI//awBz/0gAV/8lAFX/AABJ3AAAPbkAADGWAAAlcwAAGVAAANT/1ACx/7EAjv+OAGv/awBI/0gAJf8lAAD+AAAA3AAAALkAAACWAAAAcwAAAFAAANT/4wCx/8cAjv+rAGv/jwBI/3MAJf9XAAD/VQAA3EkAALk9AACWMQAAcyUAAFAZANT/8ACx/+IAjv/UAGv/xgBI/7gAJf+qAAD/qgAA3JIAALl6AACWYgAAc0oAAFAyANT//wCx//8Ajv//AGv//wBI//8AJf//AAD+/gAA3NwAALm5AACWlgAAc3MAAFBQAPLy8gDm5uYA2traAM7OzgDCwsIAtra2AKqqqgCenp4AkpKSAIaGhgB6enoAbm5uAGJiYgBWVlYASkpKAD4+PgAyMjIAJiYmABoaGgAODg4A8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAAAO/v7/Ly8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO/v5eXYspWJ8vIAAAAAAAAAAAAAAOvl/+X/AAAAAADv5ubl5diylYmXnPIAAAAAAAAAAAAA6//l/+UA6wAA7+fm5ubl2JWJl5ycnPIAAAAAAAAAAADr5f/l/wD36wDt5+fm5uXYiZecnOPj8gAAAAAAAAAAAOv/5f/lAOv37+fn5+fm5eWXnOPj4+Pj8gAAAAAAAAAA6+X/5f8A9+vv5efn5+fmAADj4+Pn5+fyAAAAAAAAAADr/+X/5QDr9+/l5eXn5wD//wDr6+vn5/IAAAAAAAAAAOvl/+X/APfr7+np6enpAP//AOTk6+vr8gAAAAAAAAAA6//l/+UA6/fv4+OcnJWVAADn9//k5+fyAAAAAAAAAADr/////wD36+/jnJWVienpzef35v/k5PIAAAAAAAAAAOv/////AOv36++VlYnpqdjN5+f35v/yAAAAAAAAAAAA6/////8A9+v375WJienY2M3N5/f35vLm5ubm5gAAAADr/////wD39/f374npqdjNzc3n5/fyAAAAAObn6wAAAOv/////APf39/cA7e2p2M3Nzefy8uvr6+vr5ubrAAAA6/////8A9/f39wD//+rq6urt7f///////////+sAAADr6+vr6wD39/f3AOvr6+vr6+vr6+vr6+vr6+vn6wAAAO/v7+/vAPf39/cAAAAAAAAAAAAAAAAAAAAAAADn9QDr///////vAPf39wDr5ubm5ubm5ubm5ubm5ubm6wAA6+vr6+vr6+/vAPf3AOv//////////////////+brAAAAAAAAAOvv7+/vAPcA6/8EBAQEBAQEBAQEBAT/5usAAAAAAAAAAOvv7+/vAADr/wT+hYWJiYmJe3t7BP/m6wAAAAAAAAAAAOv/////AOv/BI6ThYWJiYmJe3sE/+brAAAAAAAAAAAAAOvr6+vrAP8Ek46ThYWJiYmJewT/5usAAAAAAAAAAAAAAAAAAADr/wSOk46ThYWJiYmJBP/m6wAAAAAAAAAAAAAAAAAAAOv/BJOOk46ThYWJiYkE/+brAAAAAAAAAAAAAAAAAAAA6/8EhZOOk46ThYWJiQT/5usAAAAAAAAAAAAAAAAAAADr/wSFhZOOk46ThYWJBP/m6wAAAAAAAAAAAAAAAAAAAOv/BIWFhZOOk47+hYUE/+brAAAAAAAAAAAAAAAAAAAA6/8EBAQEBAQEBAQEBAT/5usAAAAAAAAAAAAAAAAAAADr///////////////////m6wAAAAAAAAAAAAAAAAAAAADt7e3t7e3t7e3t7e3t7e3tAAD//gf/wPgB/8BwAP/AIAB/wAAAf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAPAAAABwAAAAMAAAADAAAAAwAAAAMAAAACAAAABAAAAAfgAAAH8AAAB/gAAAf8AAAH/+AAB//gAAf/4AAH/+AAB//gAAf/4AAH/+AAB//wAAw==";
static const char* binary_New = "AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAACAAAAAgIAAgAAAAIAAgACAgAAAwMDAAICAgAAAAP8AAP8AAAD//wD/AAAA/wD/AP//AAD///8AAAAAAAAAAAAAAAAAAAAAAAC7u7u7sAAAALu7u7uwAAAAu7u7u7AAAAC7u7u7sAAAALu7u7uwAAAAu7u7u7AAAAAAAAAAAAAAAAu7sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAgA8AAIAPAACADwAAgA8AAIANAACACwAAgAcAAIAaAADA1wAA4asAAP99AAD/7wAA//8AAP/vAAD//wAA";
static const char* binary_removico = "AAABAAIAICAQAAAAAADoAgAAJgAAACAgAAAAAAAAqAgAAA4DAAAoAAAAIAAAAEAAAAABAAQAAAAAAIACAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAH////f3AAAAAAAAAAAAAH9/////f39wAAAAAAAAAId3//////f3d3AAAAAAAACIf3///+d/dmyHcAAAAAAAh3f////od2dmbIdwAAAAAIh/f///7obmZmbId3AAAACHd////+5uaId3zHd4AAAAiH9////u7mZ393yHeAAAAId3////7u7uZn93x3gAAACIf3///+7uZnf3d8d4AAAAh3f////u5n9/f3fHeAAAAIh/f///7mf393d3d3gAAACHd////+Z//3dEREd4AAAAiH9////35/f3fMxHeAAAAId3////9+d/d3fMR3gAAACIf3///3/ud3d8bEd4AAAAh3f/////fm5mxsxHeAAAAIh/f///f/fmZmzHR3gAAACHd/////9/d2bGd0d4AAAAiHd3d3d3d3d3d3dHeAAAAId3//////d3d3d3d3gAAACH94RFyIh3/3d3d3d4AAAAj4R3d3dwGBh393B3eAAAAI9GX+/nA7fwGIf3cHgAAACPB2X+cDt/B7exiPcIAAAACBd2X0G38HZ7+3CI8AAAAACB92XCEwfnZ78zcIcAAAAACB98jw0G//Z7NwOHAAAAAACBx/B3s0b/Y/A9gAAAAAAACB8BO9CBRv9DiAAAAAAAAACAiAMIMzRgiIAAAA/gB///gAD//wAAP/4AAA/+AAAD/gAAAP4AAAB+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPwAAAD+AAAA/wAAAP+AAAH/wAAD/+AAD8oAAAAIAAAAEAAAAABAAgAAAAAAIAEAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmANTw/wCx4v8AjtT/AGvG/wBIuP8AJar/AACq/wAAktwAAHq5AABilgAASnMAADJQANTj/wCxx/8Ajqv/AGuP/wBIc/8AJVf/AABV/wAASdwAAD25AAAxlgAAJXMAABlQANTU/wCxsf8Ajo7/AGtr/wBISP8AJSX/AAAA/gAAANwAAAC5AAAAlgAAAHMAAABQAOPU/wDHsf8Aq47/AI9r/wBzSP8AVyX/AFUA/wBJANwAPQC5ADEAlgAlAHMAGQBQAPDU/wDisf8A1I7/AMZr/wC4SP8AqiX/AKoA/wCSANwAegC5AGIAlgBKAHMAMgBQAP/U/wD/sf8A/47/AP9r/wD/SP8A/yX/AP4A/gDcANwAuQC5AJYAlgBzAHMAUABQAP/U8AD/seIA/47UAP9rxgD/SLgA/yWqAP8AqgDcAJIAuQB6AJYAYgBzAEoAUAAyAP/U4wD/sccA/46rAP9rjwD/SHMA/yVXAP8AVQDcAEkAuQA9AJYAMQBzACUAUAAZAP/U1AD/sbEA/46OAP9rawD/SEgA/yUlAP4AAADcAAAAuQAAAJYAAABzAAAAUAAAAP/j1AD/x7EA/6uOAP+PawD/c0gA/1clAP9VAADcSQAAuT0AAJYxAABzJQAAUBkAAP/w1AD/4rEA/9SOAP/GawD/uEgA/6olAP+qAADckgAAuXoAAJZiAABzSgAAUDIAAP//1AD//7EA//+OAP//awD//0gA//8lAP7+AADc3AAAubkAAJaWAABzcwAAUFAAAPD/1ADi/7EA1P+OAMb/awC4/0gAqv8lAKr/AACS3AAAerkAAGKWAABKcwAAMlAAAOP/1ADH/7EAq/+OAI//awBz/0gAV/8lAFX/AABJ3AAAPbkAADGWAAAlcwAAGVAAANT/1ACx/7EAjv+OAGv/awBI/0gAJf8lAAD+AAAA3AAAALkAAACWAAAAcwAAAFAAANT/4wCx/8cAjv+rAGv/jwBI/3MAJf9XAAD/VQAA3EkAALk9AACWMQAAcyUAAFAZANT/8ACx/+IAjv/UAGv/xgBI/7gAJf+qAAD/qgAA3JIAALl6AACWYgAAc0oAAFAyANT//wCx//8Ajv//AGv//wBI//8AJf//AAD+/gAA3NwAALm5AACWlgAAc3MAAFBQAPLy8gDm5uYA2traAM7OzgDCwsIAtra2AKqqqgCenp4AkpKSAIaGhgB6enoAbm5uAGJiYgBWVlYASkpKAD4+PgAyMjIAJiYmABoaGgAODg4A8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAADq6efn5+fn5+rqAAAAAAAAAAAAAAAAAAAAAAAAAAD35+Pj9vb29vbi9uPn5+oAAAAAAAAAAAAAAAAAAAAA+Afl5OLi9vb24vbi4+OC5ffqAAAAAAAAAAAAAAAAAO3352rj4/b29vYi4vbi4+MiauXn6gAAAAAAAAAAAAAA7eoH5eTi4vb29oYi4uMi6e3t7eVq9+oAAAAAAAAAAADt9+dq4+P29vb2hYb2IoeHh4dte+lq5/fsAAAAAAAAAO3qB+Xk4uL29vaFkCKHhnl5bW1te+nn9+nyAAAAAAAA7ffnauPj9vb29oWQh4Z5eW1qImpvb+nn923yAAAAAADt6gfl5OLi9vb2hZCGhnlt4yJq5Wpv7ff36/IAAAAAAO3352rj4/b29vaFkP6GeYdtbSJqB+l+5/dt8gAAAAAA7eoH5eTi4vb29oWQ/oaHbeMiauVq53739+vyAAAAAADt9+dq4+P29vb2hJCGeePjImoiagdqfuf3bfIAAAAAAO3qB+Xk4uL29vaQeYbj44LjImrlaufn9/fr8gAAAAAA7ffnauPj9vb29vbl9uLj4yJqbXtvfn7p923yAAAAAADt6gfl5OLi9vb24uWG4+OC4yJqe29vfvf36/IAAAAAAO3352rj4/b29vb25Ybp4+MiaiJqb35+6fdt8gAAAAAA7eoH5eTi4vb29uL2hofp6SIiantvb3739+vyAAAAAADt9+dq4+P29vb29uLlh21te3t7b29+fun3bfIAAAAAAO3qB+Xk4uL29vbi9uLlh21te3tvfudn9/fr8gAAAAAA7ffnauXk4+Pj4+Pj4+Pj6Yd7b28Hamfp923yAAAAAADt6gfnBwcHBwfn5+fn5+fl5Wrl5WrnZ/f36/IAAAAAAO339+Tj1tbW1tbW1tYiIuf39+cHB2rn5/dt8gAAAAAA7ffW6e3y8u7t7u3u9+fj4yIHB/f35+f39+vyAAAAAADt1u3y9wnkCeQJ53UV7RXt9+XjIvfp9/f3bfIAAAAAAO3W8u3u/4KCgufv6Woi4+cV7e3n4yL36ffr8gAAAAAA7NZ19+3u/4Lk7+lqIuPtde4iIhXt6eMi6e3yAAAAAAAA7fLnau3u/+91aiLjFXkJeRX/IiJ17erj6fIAAAAAAAAA7ev2au3v9+sVde+C5IIJeRX/dXl5Fesi8gAAAAAAAAAA7ff2avcVFWrldRWC/4KCCRV5CXXu6wfyAAAAAAAAAAAA7fcVFfdqju8T6RXq/46C5IJF7vfq8gAAAAAAAAAAAAAA7eztE//v8ukiIu3v6v+O8hPs7e0AAAAAAAAAAAAAAAAAAAAAEwDt7RMHFXXo7+3t7e0AAAAAAAD+AH//+AAP//AAA//gAAD/4AAAP+AAAA/gAAAH4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA+AAAAPgAAAD4AAAA/AAAAP4AAAD/AAAA/4AAAf/AAAP//QAPw==";
static const char* binary_repairic = "AAABAAIAICAQAAAAAADoAgAAJgAAACAgAAAAAAAAqAgAAA4DAAAoAAAAIAAAAEAAAAABAAQAAAAAAIACAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAIiAAAAAAAAAAAAAAAAAAIh3u7oAAAAAAAAAAAAAAAj393u6qgAAAAAAAAAAAACHj3+7qqdwAAAAAAAAAAAAiHj3e6p3cAAAAAAAAAL6KIeHj3und+4AAAAAAAAC+ih4eHgAp+7uAAAAAAAAAvooh4eA/w7udwAAAAAAAAL6KHd+4P8IeHgAAAAAAAAC+ih+564Ah4eHB3d3dwAAAvoo7nruv/h4eAAAAHeAAAL6IIeu7r9/h4CIiIh3gAAC+iCK7uu39/hw/////4AAAvog+O67t39/CIiIiIeAAAL6IPmIu7d3AAAAAAAAcAAC+iD5EIiIiHd3d3d3eAAAAv9w+RAI/////////3gAAAAiAfkQCPRERERERE94AAAADwF/kAj053ZmbMxPeAAAAAcAERAI9P53ZmbMT3gAAAAAAIcACPTv53ZmbE94AAAAiICHAAj0/v53ZmZPeACHAHd4APAI9O/v53ZmT3gAj4f3d48ACPR+/v53Zk94AI+I///wAAj0d+/v53ZPeACIAIiIBwAI9Hd+/v53T3gAAAAAAIcACPRERERERE94AAAAAAh3gAj/////////eAAAAAAId4AAiIiIiIiIiIgAAAAACPeAAAAAAAAAAAAAAAAAAAj3gAAAAAAAAAAAAAAAAAAIiIAAAAAAAAAAAAAA//A////AD///gAf//wAD//EAA//gAAH/4AAB/+AAAf/gAAAD4AAAAeAAAADgAAAA4AAAAOAAAADgAAAA4AAAAeAIAAHwCAAB8AgAAfEYAAHxGAABEAgAAQAIAAEAGAABABgAATAYAAH/GAAB/ggAAf4MAAP+D////g////4P//8oAAAAIAAAAEAAAAABAAgAAAAAAIAEAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAMDAwADA3MAA8MqmANTw/wCx4v8AjtT/AGvG/wBIuP8AJar/AACq/wAAktwAAHq5AABilgAASnMAADJQANTj/wCxx/8Ajqv/AGuP/wBIc/8AJVf/AABV/wAASdwAAD25AAAxlgAAJXMAABlQANTU/wCxsf8Ajo7/AGtr/wBISP8AJSX/AAAA/gAAANwAAAC5AAAAlgAAAHMAAABQAOPU/wDHsf8Aq47/AI9r/wBzSP8AVyX/AFUA/wBJANwAPQC5ADEAlgAlAHMAGQBQAPDU/wDisf8A1I7/AMZr/wC4SP8AqiX/AKoA/wCSANwAegC5AGIAlgBKAHMAMgBQAP/U/wD/sf8A/47/AP9r/wD/SP8A/yX/AP4A/gDcANwAuQC5AJYAlgBzAHMAUABQAP/U8AD/seIA/47UAP9rxgD/SLgA/yWqAP8AqgDcAJIAuQB6AJYAYgBzAEoAUAAyAP/U4wD/sccA/46rAP9rjwD/SHMA/yVXAP8AVQDcAEkAuQA9AJYAMQBzACUAUAAZAP/U1AD/sbEA/46OAP9rawD/SEgA/yUlAP4AAADcAAAAuQAAAJYAAABzAAAAUAAAAP/j1AD/x7EA/6uOAP+PawD/c0gA/1clAP9VAADcSQAAuT0AAJYxAABzJQAAUBkAAP/w1AD/4rEA/9SOAP/GawD/uEgA/6olAP+qAADckgAAuXoAAJZiAABzSgAAUDIAAP//1AD//7EA//+OAP//awD//0gA//8lAP7+AADc3AAAubkAAJaWAABzcwAAUFAAAPD/1ADi/7EA1P+OAMb/awC4/0gAqv8lAKr/AACS3AAAerkAAGKWAABKcwAAMlAAAOP/1ADH/7EAq/+OAI//awBz/0gAV/8lAFX/AABJ3AAAPbkAADGWAAAlcwAAGVAAANT/1ACx/7EAjv+OAGv/awBI/0gAJf8lAAD+AAAA3AAAALkAAACWAAAAcwAAAFAAANT/4wCx/8cAjv+rAGv/jwBI/3MAJf9XAAD/VQAA3EkAALk9AACWMQAAcyUAAFAZANT/8ACx/+IAjv/UAGv/xgBI/7gAJf+qAAD/qgAA3JIAALl6AACWYgAAc0oAAFAyANT//wCx//8Ajv//AGv//wBI//8AJf//AAD+/gAA3NwAALm5AACWlgAAc3MAAFBQAPLy8gDm5uYA2traAM7OzgDCwsIAtra2AKqqqgCenp4AkpKSAIaGhgB6enoAbm5uAGJiYgBWVlYASkpKAD4+PgAyMjIAJiYmABoaGgAODg4A8Pv/AKSgoACAgIAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAO/v7/Ly8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO/v5eXYspWJ8vIAAAAAAAAAAAAAAAAAAAAAAAAAAADv5ubl5diylYmXnPIAAAAAAAAAAAAAAAAAAAAAAAAA7+fm5ubl2JWJl5ycnPIAAAAAAAAAAAAAAAAAAMnJyQDt5+fm5uXYiZecnOPj8gAAAAAAAAAAAAAAAAC7vsK67+fn5+fm5eWXnOPj4+Pj8gAAAAAAAAAAAAAAALu+xLrv5efn5+fmAADj4+Pn5+fyAAAAAAAAAAAAAAAAu77Cuu/l5eXn5wD//wDr6+vn5/IAAAAAAAAAAAAAAAC7vsS67+np6enpAP//AOTk6+vr8gAAAAAAAAAAAAAAALu+wrrv4+OcnJWVAADn9//k5+fy5+fn5+fn5wAAAAAAu77Euu/jnJWVienpzef35v/k5PIAAAAAAObn6wAAAAC7vsK6ye+VlYnpqdjN5+f35v/y6+vr6+vr5ufrAAAAALu+xLrJ75WJienY2M3N5/f35vLm5ubm5ubm5+sAAAAAu77CuskX74npqdjNzc3n5/fy6+vr6+vr6+vn6wAAAAC79sS6yRf57e2p2M3Nzefy8gAAAAAAAAAAAADn9QAAALv2wrrJF/kqLerq6urt7ebm5ubm5ubm5ubm6wAAAAAAu/b2vMkX+SotAOv//////////////////+brAAAAAAAAu7vzARf5Ki0A6/8EBAQEBAQEBAQEBAT/5usAAAAAAADw4vMB/xf5LQDr/wT+hYWJiYmJe3t7BP/m6wAAAAAAAPDn8wABAQEAAOv/BI6ThYWJiYmJe3sE/+brAAAAAAAA8PLzAOvm8gAA6/8Ek46ThYWJiYmJewT/5usAAPT09ADs7Oz06+b09ADr/wSOk46ThYWJiYmJBP/m6wAA6eTx9Ojm6Oz09OL0AOv/BJOOk46ThYWJiYkE/+brAADp4unk5Obm6Ozi9AAA6/8EhZOOk46ThYWJiQT/5usAAOn26eni4+Lj4vTyAADr/wSFhZOOk46ThYWJBP/m6wAA6ekAAOnp6en05fIAAOv/BIWFhZOOk47+hYUE/+brAAAAAAAAAAAAAOvk8gAA6/8EBAQEBAQEBAQEBAT/5usAAAAAAAAAAADp5uXr8gDr///////////////////m6wAAAAAAAAAAAOnk5OvyAADt7e3t7e3t7e3t7e3t7e3tAAAAAAAAAAAA6f/l6/IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADp4uTr8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOnp6enyAAAAAAAAAAAAAAAAAAAAAAAAAAD/8D///8AP//+AB///AAP/8QAD/+AAAf/gAAH/4AAB/+AAAAPgAAAB4AAAAOAAAADgAAAA4AAAAOAAAADgAAAB4AgAAfAIAAHwCAAB8RgAAfEYAAEQCAABAAgAAQAYAAEAGAABMBgAAf8YAAH+CAAB/gwAA/4P///+D////g///w==";
static const char* binary_Up = "AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAACAAAAAgIAAgAAAAIAAgACAgAAAwMDAAICAgAAAAP8AAP8AAAD//wD/AAAA/wD/AP//AAD///8AAAAAAAAAAAAAAAAAAAAAAAC7u7u7u7uwALu7u7u7u7AAu7sAAAC7sAC7uwu7u7uwALu7C7u7u7AAuwAAC7u7sAC7sAC7u7uwALu7C7u7u7AAu7u7u7u7sAAAAAAAAAAAAAu7uwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIABAADAfwAA4P8AAP//AAD//wAA";

static std::shared_ptr<DataBuffer> createBmpBGRA8(int width, int height, bool banner)
{
	BITMAPV5HEADER bmpheader = {
		.bV5Size = sizeof(BITMAPV5HEADER),
		.bV5Width = width,
		.bV5Height = -height,
		.bV5Planes = 1,
		.bV5BitCount = 32,
		.bV5Compression = BI_BITFIELDS,
		.bV5SizeImage = static_cast<DWORD>(width * height * 4),
		.bV5RedMask = 0x00ff0000,
		.bV5GreenMask = 0x0000ff00,
		.bV5BlueMask = 0x000000ff,
		.bV5AlphaMask = 0xff000000,
		.bV5CSType = LCS_sRGB,
		.bV5Intent = LCS_GM_GRAPHICS
	};

	uint32_t pixelsOffset = 14 + sizeof(BITMAPV5HEADER);
	uint32_t fileSize = pixelsOffset + bmpheader.bV5SizeImage;
	auto bmp = DataBuffer::create(fileSize);

	uint8_t* bmpfileheader = bmp->data<uint8_t>();
	bmpfileheader[0] = 'B';
	bmpfileheader[1] = 'M';
	bmpfileheader[2] = fileSize & 0xff;
	bmpfileheader[3] = (fileSize >> 8) & 0xff;
	bmpfileheader[4] = (fileSize >> 16) & 0xff;
	bmpfileheader[5] = (fileSize >> 24) & 0xff;
	bmpfileheader[6] = 0;
	bmpfileheader[7] = 0;
	bmpfileheader[8] = 0;
	bmpfileheader[9] = 0;
	bmpfileheader[10] = pixelsOffset & 0xff;
	bmpfileheader[11] = (pixelsOffset >> 8) & 0xff;
	bmpfileheader[12] = (pixelsOffset >> 16) & 0xff;
	bmpfileheader[13] = (pixelsOffset >> 24) & 0xff;

	memcpy(bmp->data() + 14, &bmpheader, sizeof(BITMAPV5HEADER));

	uint32_t* pixels = (uint32_t*)(bmp->data() + 14 + sizeof(BITMAPV5HEADER));
	for (int y = 0; y < height; y++)
	{
		uint32_t* line = pixels + y * width;
		for (int x = 0; x < width; x++)
		{
			if (banner)
				line[x] = 0xFFFFFFFF;
			else
				line[x] = x < 165 ? 0xFFB0E0E6 : 0xFFFFFFFF;
		}
	}
	return bmp;
}


static std::shared_ptr<DataBuffer> createBmpPalette(int width, int height, bool banner)
{
	BITMAPV5HEADER bmpheader = {
		.bV5Size = sizeof(BITMAPV5HEADER),
		.bV5Width = width,
		.bV5Height = -height,
		.bV5Planes = 1,
		.bV5BitCount = 8,
		.bV5Compression = BI_RGB,
		.bV5CSType = LCS_sRGB,
		.bV5Intent = LCS_GM_GRAPHICS
	};

	int pitch = (width + 3) / 4 * 4;

	RGBQUAD colors[256] = {};
	colors[0].rgbRed = 176;
	colors[0].rgbGreen = 224;
	colors[0].rgbBlue = 230;
	colors[1].rgbRed = 255;
	colors[1].rgbGreen = 255;
	colors[1].rgbBlue = 255;

	uint32_t paletteOffset = 14 + sizeof(BITMAPV5HEADER);
	uint32_t pixelsOffset = paletteOffset + sizeof(RGBQUAD) * 256;
	uint32_t fileSize = pixelsOffset + pitch * height;

	auto bmp = DataBuffer::create(fileSize);

	uint8_t* bmpfileheader = bmp->data<uint8_t>();
	bmpfileheader[0] = 'B';
	bmpfileheader[1] = 'M';
	bmpfileheader[2] = fileSize & 0xff;
	bmpfileheader[3] = (fileSize >> 8) & 0xff;
	bmpfileheader[4] = (fileSize >> 16) & 0xff;
	bmpfileheader[5] = (fileSize >> 24) & 0xff;
	bmpfileheader[6] = 0;
	bmpfileheader[7] = 0;
	bmpfileheader[8] = 0;
	bmpfileheader[9] = 0;
	bmpfileheader[10] = pixelsOffset & 0xff;
	bmpfileheader[11] = (pixelsOffset >> 8) & 0xff;
	bmpfileheader[12] = (pixelsOffset >> 16) & 0xff;
	bmpfileheader[13] = (pixelsOffset >> 24) & 0xff;

	memcpy(bmp->data() + 14, &bmpheader, sizeof(BITMAPV5HEADER));
	memcpy(bmp->data() + paletteOffset, colors, sizeof(RGBQUAD) * 256);

	uint8_t* pixels = (uint8_t*)(bmp->data() + pixelsOffset);
	for (int y = 0; y < height; y++)
	{
		uint8_t* line = pixels + y * pitch;
		for (int x = 0; x < width; x++)
		{
			if (banner)
				line[x] = 1;
			else
				line[x] = x < 165 ? 0 : 1;
		}
	}
	return bmp;
}

MSIDialogs::MSIDialogs()
{
	binary =
	{
		{.name = "bannrbmp", .data = createBmpPalette(500, 63, true) },
		{.name = "completi", .data = Base64::decode(binary_completi) },
		{.name = "custicon", .data = Base64::decode(binary_custicon) },
		{.name = "dlgbmp", .data = createBmpPalette(503, 314, false) },
		{.name = "exclamic", .data = Base64::decode(binary_exclamic) },
		{.name = "info", .data = Base64::decode(binary_info) },
		{.name = "insticon", .data = Base64::decode(binary_insticon) },
		{.name = "New", .data = Base64::decode(binary_New) },
		{.name = "removico", .data = Base64::decode(binary_removico) },
		{.name = "repairic", .data = Base64::decode(binary_repairic) },
		{.name = "Up", .data = Base64::decode(binary_Up) },
	};
}

void MSIDialogs::createTables(MSIDatabase* db, std::vector<MSIProperty>& propertyList)
{
	propertyList.insert(propertyList.end(), property.begin(), property.end());

	std::vector<MSIDialog> dialogs;
	std::vector<MSIControl> controls;
	std::vector<MSIControlCondition> controlCondition;
	std::vector<MSIControlEvent> controlEvent;
	std::vector<MSIEventMapping> eventMapping;

	addDialog(adminWelcomeDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(exitDialog, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(fatalError, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(prepareDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(progressDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(userExit, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(adminBrowseDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(adminInstallPointDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(adminRegistrationDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(browseDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(cancelDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(customizeDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(diskCostDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(errorDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(filesInUse, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(licenseAgreementDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(maintenanceTypeDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(maintenanceWelcomeDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(msiRMFilesInUse, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(outOfDiskDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(outOfRbDiskDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(resumeDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(setupTypeDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(userRegistrationDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(verifyReadyDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(verifyRemoveDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(verifyRepairDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(waitForCostingDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(welcomeDlg, dialogs, controls, controlCondition, controlEvent, eventMapping);
	addDialog(welcomeDlgLink, dialogs, controls, controlCondition, controlEvent, eventMapping);

	db->createTable(dialogs);
	db->createTable(controls);
	db->createTable(controlCondition);
	db->createTable(controlEvent);
	db->createTable(eventMapping);

	db->createTable(textStyle);
	db->createTable(uiText);
	db->createTable(bbControl);
	db->createTable(billboard);
	db->createTable(checkBox);
	db->createTable(radioButton);
	db->createTable(comboBox);
	db->createTable(listBox);
	db->createTable(listView);
	db->createTable(binary);
}

#endif
