
#include "Precomp.h"
#include "MSISequence.h"

MSISequences::MSISequences()
{
#if 1 // "Recommended" sequences from the docs

	installUISequence =
	{
		{.action = "FatalError", .sequence = -3 },
		{.action = "UserExit", .sequence = -2 },
		{.action = "ExitDialog", .sequence = -1 },
		{.action = "LaunchConditions", .sequence = 100 },
		{.action = "PrepareDlg", .sequence = 140 },
		{.action = "FindRelatedProducts", .sequence = 200 },
		{.action = "AppSearch", .sequence = 400 },
		{.action = "CCPSearch", .condition = "NOT Installed", .sequence = 500 },
		{.action = "RMCCPSearch", .condition = "NOT Installed", .sequence = 600 },
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "MigrateFeatureStates", .sequence = 1200 },
		{.action = "WelcomeDlg", .condition = "NOT Installed AND VersionHandler < \"5.00\"", .sequence = 1230 },
		{.action = "WelcomeDlgLink", .condition = "NOT Installed AND VersionHandler >= \"5.00\"", .sequence = 1231 },
		{.action = "ResumeDlg", .condition = "Installed AND (RESUME OR Preselected)", .sequence = 1240 },
		{.action = "MaintenanceWelcomeDlg", .condition = "Installed AND NOT RESUME AND NOT Preselected", .sequence = 1250 },
		{.action = "ProgressDlg", .sequence = 1280 },
		{.action = "ExecuteAction", .sequence = 1300 },
	};

	installExecuteSequence =
	{
		{.action = "LaunchConditions", .sequence = 100 },
		{.action = "AppSearch", .sequence = 400 },
		{.action = "CCPSearch", .condition = "NOT Installed", .sequence = 500 },
		{.action = "RMCCPSearch", .condition = "NOT Installed", .sequence = 600 },
		{.action = "ValidateProductID", .sequence = 700 },
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "SetODBCFolders", .sequence = 1100 },
		{.action = "InstallValidate", .sequence = 1400 },
		{.action = "InstallInitialize", .sequence = 1500 },
		{.action = "AllocateRegistrySpace", .condition = "NOT Installed", .sequence = 1550 },
		{.action = "ProcessComponents", .sequence = 1600 },
		{.action = "UnpublishComponents", .sequence = 1700 },
		{.action = "UnpublishFeatures", .sequence = 1800 },
		{.action = "StopServices", .condition = "VersionNT", .sequence = 1900 },
		{.action = "DeleteServices", .condition = "VersionNT", .sequence = 2000 },
		{.action = "UnregisterComPlus", .sequence = 2100 },
		{.action = "SelfUnregModules", .sequence = 2200 },
		{.action = "UnregisterTypeLibraries", .sequence = 2300 },
		{.action = "RemoveODBC", .sequence = 2400 },
		{.action = "UnregisterFonts", .sequence = 2500 },
		{.action = "RemoveRegistryValues", .sequence = 2600 },
		{.action = "UnregisterClassInfo", .sequence = 2700 },
		{.action = "UnregisterExtensionInfo", .sequence = 2800 },
		{.action = "UnregisterProgIdInfo", .sequence = 2900 },
		{.action = "UnregisterMIMEInfo", .sequence = 3000 },
		{.action = "RemoveIniValues", .sequence = 3100 },
		{.action = "RemoveShortcuts", .sequence = 3200 },
		{.action = "RemoveEnvironmentStrings", .sequence = 3300 },
		{.action = "RemoveDuplicateFiles", .sequence = 3400 },
		{.action = "RemoveFiles", .sequence = 3500 },
		{.action = "RemoveFolders", .sequence = 3600 },
		{.action = "CreateFolders", .sequence = 3700 },
		{.action = "MoveFiles", .sequence = 3800 },
		{.action = "InstallFiles", .sequence = 4000 },
		{.action = "PatchFiles", .sequence = 4090 },
		{.action = "DuplicateFiles", .sequence = 4210 },
		{.action = "BindImage", .sequence = 4300 },
		{.action = "CreateShortcuts", .sequence = 4500 },
		{.action = "RegisterClassInfo", .sequence = 4600 },
		{.action = "RegisterExtensionInfo", .sequence = 4700 },
		{.action = "RegisterProgIdInfo", .sequence = 4800 },
		{.action = "RegisterMIMEInfo", .sequence = 4900 },
		{.action = "WriteRegistryValues", .sequence = 5000 },
		{.action = "WriteIniValues", .sequence = 5100 },
		{.action = "WriteEnvironmentStrings", .sequence = 5200 },
		{.action = "RegisterFonts", .sequence = 5300 },
		{.action = "InstallODBC", .sequence = 5400 },
		{.action = "RegisterTypeLibraries", .sequence = 5500 },
		{.action = "SelfRegModules", .sequence = 5600 },
		{.action = "RegisterComPlus", .sequence = 5700 },
		{.action = "InstallServices", .condition = "VersionNT", .sequence = 5800 },
		{.action = "StartServices", .condition = "VersionNT", .sequence = 5900 },
		{.action = "RegisterUser", .sequence = 6000 },
		{.action = "RegisterProduct", .sequence = 6100 },
		{.action = "PublishComponents", .sequence = 6200 },
		{.action = "PublishFeatures", .sequence = 6300 },
		{.action = "PublishProduct", .sequence = 6400 },
		{.action = "InstallFinalize", .sequence = 6600 }
	};

	adminUISequence =
	{
		{.action = "FatalError", .sequence = -3 },
		{.action = "UserExit", .sequence = -2 },
		{.action = "ExitDialog", .sequence = -1 },
		{.action = "PrepareDlg", .sequence = 140 },
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "AdminWelcomeDlg", .sequence = 1230 },
		{.action = "ProgressDlg", .sequence = 1280 },
		{.action = "ExecuteAction", .sequence = 1300 }
	};

	adminExecuteSequence =
	{
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "InstallValidate", .sequence = 1400 },
		{.action = "InstallInitialize", .sequence = 1500 },
		{.action = "InstallAdminPackage", .sequence = 3900 },
		{.action = "InstallFiles", .sequence = 4000 },
		{.action = "InstallFinalize", .sequence = 6600 }
	};

	advtExecuteSequence =
	{
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "InstallValidate", .sequence = 1400 },
		{.action = "InstallInitialize", .sequence = 1500 },
		{.action = "CreateShortcuts", .sequence = 4500 },
		{.action = "RegisterClassInfo", .sequence = 4600 },
		{.action = "RegisterExtensionInfo", .sequence = 4700 },
		{.action = "RegisterProgIdInfo", .sequence = 4800 },
		{.action = "RegisterMIMEInfo", .sequence = 4900 },
		{.action = "PublishComponents", .sequence = 6200 },
		{.action = "PublishFeatures", .sequence = 6300 },
		{.action = "PublishProduct", .sequence = 6400 },
		{.action = "InstallFinalize", .sequence = 6600 }
	};

#else // UISample.msi sequences

	installExecuteSequence =
	{
		{.action = "LaunchConditions", .sequence = 100 },
		{.action = "FindRelatedProducts", .sequence = 200 },
		{.action = "AppSearch", .sequence = 400 },
		{.action = "CCPSearch", .condition = "NOT Installed", .sequence = 500 },
		{.action = "RMCCPSearch", .condition = "NOT Installed", .sequence = 600 },
		{.action = "ValidateProductID", .sequence = 700 },
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "SetODBCFolders", .sequence = 1100 },
		{.action = "MigrateFeatureStates", .sequence = 1200 },
		{.action = "InstallValidate", .sequence = 1400 },
		{.action = "InstallInitialize", .sequence = 1500 },
		{.action = "AllocateRegistrySpace", .condition = "NOT Installed", .sequence = 1550 },
		{.action = "ProcessComponents", .sequence = 1600 },
		{.action = "UnpublishComponents", .sequence = 1700 },
		{.action = "UnpublishFeatures", .sequence = 1800 },
		{.action = "StopServices", .condition = "VersionNT", .sequence = 1900 },
		{.action = "DeleteServices", .condition = "VersionNT", .sequence = 2000 },
		{.action = "UnregisterComPlus", .sequence = 2100 },
		{.action = "SelfUnregModules", .sequence = 2200 },
		{.action = "UnregisterTypeLibraries", .sequence = 2300 },
		{.action = "RemoveODBC", .sequence = 2400 },
		{.action = "UnregisterFonts", .sequence = 2500 },
		{.action = "RemoveRegistryValues", .sequence = 2600 },
		{.action = "UnregisterClassInfo", .sequence = 2700 },
		{.action = "UnregisterExtensionInfo", .sequence = 2800 },
		{.action = "UnregisterProgIdInfo", .sequence = 2900 },
		{.action = "UnregisterMIMEInfo", .sequence = 3000 },
		{.action = "RemoveIniValues", .sequence = 3100 },
		{.action = "RemoveShortcuts", .sequence = 3200 },
		{.action = "RemoveEnvironmentStrings", .sequence = 3300 },
		{.action = "RemoveDuplicateFiles", .sequence = 3400 },
		{.action = "RemoveFiles", .sequence = 3500 },
		{.action = "RemoveFolders", .sequence = 3600 },
		{.action = "CreateFolders", .sequence = 3700 },
		{.action = "MoveFiles", .sequence = 3800 },
		{.action = "InstallFiles", .sequence = 4000 },
		{.action = "PatchFiles", .sequence = 4090 },
		{.action = "DuplicateFiles", .sequence = 4210 },
		{.action = "BindImage", .sequence = 4300 },
		{.action = "CreateShortcuts", .sequence = 4500 },
		{.action = "RegisterClassInfo", .sequence = 4600 },
		{.action = "RegisterExtensionInfo", .sequence = 4700 },
		{.action = "RegisterProgIdInfo", .sequence = 4800 },
		{.action = "RegisterMIMEInfo", .sequence = 4900 },
		{.action = "WriteRegistryValues", .sequence = 5000 },
		{.action = "WriteIniValues", .sequence = 5100 },
		{.action = "WriteEnvironmentStrings", .sequence = 5200 },
		{.action = "RegisterFonts", .sequence = 5300 },
		{.action = "InstallODBC", .sequence = 5400 },
		{.action = "RegisterTypeLibraries", .sequence = 5500 },
		{.action = "SelfRegModules", .sequence = 5600 },
		{.action = "RegisterComPlus", .sequence = 5700 },
		{.action = "InstallServices", .condition = "VersionNT", .sequence = 5800 },
		{.action = "StartServices", .condition = "VersionNT", .sequence = 5900 },
		{.action = "RegisterUser", .sequence = 6000 },
		{.action = "RegisterProduct", .sequence = 6100 },
		{.action = "PublishComponents", .sequence = 6200 },
		{.action = "PublishFeatures", .sequence = 6300 },
		{.action = "PublishProduct", .sequence = 6400 },
		{.action = "InstallFinalize", .sequence = 6600 },
		{.action = "RemoveExistingProducts", .sequence = 6700 },
	};

	installUISequence =
	{
		{.action = "FatalError", .sequence = -3 },
		{.action = "UserExit", .sequence = -2 },
		{.action = "ExitDialog", .sequence = -1 },
		{.action = "LaunchConditions", .sequence = 100 },
		{.action = "PrepareDlg", .sequence = 140 },
		{.action = "FindRelatedProducts", .sequence = 200 },
		{.action = "AppSearch", .sequence = 400 },
		{.action = "CCPSearch", .condition = "NOT Installed", .sequence = 500 },
		{.action = "RMCCPSearch", .condition = "NOT Installed", .sequence = 600 },
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "MigrateFeatureStates", .sequence = 1200 },
		{.action = "WelcomeDlg", .condition = "NOT Installed AND VersionHandler < \"5.00\"", .sequence = 1230 },
		{.action = "WelcomeDlgLink", .condition = "NOT Installed AND VersionHandler >= \"5.00\"", .sequence = 1231 },
		{.action = "ResumeDlg", .condition = "Installed AND (RESUME OR Preselected)", .sequence = 1240 },
		{.action = "MaintenanceWelcomeDlg", .condition = "Installed AND NOT RESUME AND NOT Preselected", .sequence = 1250 },
		{.action = "ProgressDlg", .sequence = 1280 },
		{.action = "ExecuteAction", .sequence = 1300 },
	};

	adminExecuteSequence =
	{
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "InstallValidate", .sequence = 1400 },
		{.action = "InstallInitialize", .sequence = 1500 },
		{.action = "InstallAdminPackage", .sequence = 3900 },
		{.action = "InstallFiles", .sequence = 4000 },
		{.action = "InstallFinalize", .sequence = 6600 },
	};

	adminUISequence =
	{
		{.action = "FatalError", .sequence = -3 },
		{.action = "UserExit", .sequence = -2 },
		{.action = "ExitDialog", .sequence = -1 },
		{.action = "PrepareDlg", .sequence = 140 },
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "FileCost", .sequence = 900 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "AdminWelcomeDlg", .sequence = 1230 },
		{.action = "ProgressDlg", .sequence = 1280 },
		{.action = "ExecuteAction", .sequence = 1300 },
	};

	advtExecuteSequence =
	{
		{.action = "CostInitialize", .sequence = 800 },
		{.action = "CostFinalize", .sequence = 1000 },
		{.action = "InstallValidate", .sequence = 1400 },
		{.action = "InstallInitialize", .sequence = 1500 },
		{.action = "CreateShortcuts", .sequence = 4500 },
		{.action = "RegisterClassInfo", .sequence = 4600 },
		{.action = "RegisterExtensionInfo", .sequence = 4700 },
		{.action = "RegisterProgIdInfo", .sequence = 4800 },
		{.action = "RegisterMIMEInfo", .sequence = 4900 },
		{.action = "PublishComponents", .sequence = 6200 },
		{.action = "PublishFeatures", .sequence = 6300 },
		{.action = "PublishProduct", .sequence = 6400 },
		{.action = "InstallFinalize", .sequence = 6600 },
	};
#endif

	actionText =
	{
		{.action = "InstallValidate", .description = "Validating install" },
		{.action = "InstallFiles", .description = "Copying new files", .template_ = "File: [1],  Directory: [9],  Size: [6]" },
		{.action = "InstallAdminPackage", .description = "Copying network install files", .template_ = "File: [1], Directory: [9], Size: [6]" },
		{.action = "FileCost", .description = "Computing space requirements" },
		{.action = "CostInitialize", .description = "Computing space requirements" },
		{.action = "CostFinalize", .description = "Computing space requirements" },
		{.action = "CreateShortcuts", .description = "Creating shortcuts", .template_ = "Shortcut: [1]" },
		{.action = "PublishComponents", .description = "Publishing Qualified Components", .template_ = "Component ID: [1], Qualifier: [2]" },
		{.action = "PublishFeatures", .description = "Publishing Product Features", .template_ = "Feature: [1]" },
		{.action = "PublishProduct", .description = "Publishing product information" },
		{.action = "RegisterClassInfo", .description = "Registering Class servers", .template_ = "Class Id: [1]" },
		{.action = "RegisterExtensionInfo", .description = "Registering extension servers", .template_ = "Extension: [1]" },
		{.action = "RegisterMIMEInfo", .description = "Registering MIME info", .template_ = "MIME Content Type: [1], Extension: [2]" },
		{.action = "RegisterProgIdInfo", .description = "Registering program identifiers", .template_ = "ProgId: [1]" },
		{.action = "AllocateRegistrySpace", .description = "Allocating registry space", .template_ = "Free space: [1]" },
		{.action = "AppSearch", .description = "Searching for installed applications", .template_ = "Property: [1], Signature: [2]" },
		{.action = "BindImage", .description = "Binding executables", .template_ = "File: [1]" },
		{.action = "CCPSearch", .description = "Searching for qualifying products" },
		{.action = "CreateFolders", .description = "Creating folders", .template_ = "Folder: [1]" },
		{.action = "DeleteServices", .description = "Deleting services", .template_ = "Service: [1]" },
		{.action = "DuplicateFiles", .description = "Creating duplicate files", .template_ = "File: [1],  Directory: [9],  Size: [6]" },
		{.action = "FindRelatedProducts", .description = "Searching for related applications", .template_ = "Found application: [1]" },
		{.action = "InstallODBC", .description = "Installing ODBC components" },
		{.action = "InstallServices", .description = "Installing new services", .template_ = "Service: [2]" },
		{.action = "LaunchConditions", .description = "Evaluating launch conditions" },
		{.action = "MigrateFeatureStates", .description = "Migrating feature states from related applications", .template_ = "Application: [1]" },
		{.action = "MoveFiles", .description = "Moving files", .template_ = "File: [1],  Directory: [9],  Size: [6]" },
		{.action = "PatchFiles", .description = "Patching files", .template_ = "File: [1],  Directory: [2],  Size: [3]" },
		{.action = "ProcessComponents", .description = "Updating component registration" },
		{.action = "RegisterComPlus", .description = "Registering COM+ Applications and Components", .template_ = "AppId: [1]{{, AppType: [2], Users: [3], RSN: [4]}}" },
		{.action = "RegisterFonts", .description = "Registering fonts", .template_ = "Font: [1]" },
		{.action = "RegisterProduct", .description = "Registering product", .template_ = "[1]" },
		{.action = "RegisterTypeLibraries", .description = "Registering type libraries", .template_ = "LibID: [1]" },
		{.action = "RegisterUser", .description = "Registering user", .template_ = "[1]" },
		{.action = "RemoveDuplicateFiles", .description = "Removing duplicated files", .template_ = "File: [1], Directory: [9]" },
		{.action = "RemoveEnvironmentStrings", .description = "Updating environment strings", .template_ = "Name: [1], Value: [2], Action [3]" },
		{.action = "RemoveExistingProducts", .description = "Removing applications", .template_ = "Application: [1], Command line: [2]" },
		{.action = "RemoveFiles", .description = "Removing files", .template_ = "File: [1], Directory: [9]" },
		{.action = "RemoveFolders", .description = "Removing folders", .template_ = "Folder: [1]" },
		{.action = "RemoveIniValues", .description = "Removing INI files entries", .template_ = "File: [1],  Section: [2],  Key: [3], Value: [4]" },
		{.action = "RemoveODBC", .description = "Removing ODBC components" },
		{.action = "RemoveRegistryValues", .description = "Removing system registry values", .template_ = "Key: [1], Name: [2]" },
		{.action = "RemoveShortcuts", .description = "Removing shortcuts", .template_ = "Shortcut: [1]" },
		{.action = "RMCCPSearch", .description = "Searching for qualifying products" },
		{.action = "SelfRegModules", .description = "Registering modules", .template_ = "File: [1], Folder: [2]" },
		{.action = "SelfUnregModules", .description = "Unregistering modules", .template_ = "File: [1], Folder: [2]" },
		{.action = "SetODBCFolders", .description = "Initializing ODBC directories" },
		{.action = "StartServices", .description = "Starting services", .template_ = "Service: [1]" },
		{.action = "StopServices", .description = "Stopping services", .template_ = "Service: [1]" },
		{.action = "UnpublishComponents", .description = "Unpublishing Qualified Components", .template_ = "Component ID: [1], Qualifier: [2]" },
		{.action = "UnpublishFeatures", .description = "Unpublishing Product Features", .template_ = "Feature: [1]" },
		{.action = "UnregisterClassInfo", .description = "Unregister Class servers", .template_ = "Class Id: [1]" },
		{.action = "UnregisterComPlus", .description = "Unregistering COM+ Applications and Components", .template_ = "AppId: [1]{{, AppType: [2]}}" },
		{.action = "UnregisterExtensionInfo", .description = "Unregistering extension servers", .template_ = "Extension: [1]" },
		{.action = "UnregisterFonts", .description = "Unregistering fonts", .template_ = "Font: [1]" },
		{.action = "UnregisterMIMEInfo", .description = "Unregistering MIME info", .template_ = "MIME Content Type: [1], Extension: [2]" },
		{.action = "UnregisterProgIdInfo", .description = "Unregistering program identifiers", .template_ = "ProgId: [1]" },
		{.action = "UnregisterTypeLibraries", .description = "Unregistering type libraries", .template_ = "LibID: [1]" },
		{.action = "WriteEnvironmentStrings", .description = "Updating environment strings", .template_ = "Name: [1], Value: [2], Action [3]" },
		{.action = "WriteIniValues", .description = "Writing INI files values", .template_ = "File: [1],  Section: [2],  Key: [3], Value: [4]" },
		{.action = "WriteRegistryValues", .description = "Writing system registry values", .template_ = "Key: [1], Name: [2], Value: [3]" },
		{.action = "Advertise", .description = "Advertising application" },
		{.action = "GenerateScript", .description = "Generating script operations for action:", .template_ = "[1]" },
		{.action = "InstallSFPCatalogFile", .description = "Installing system catalog", .template_ = "File: [1],  Dependencies: [2]" },
		{.action = "MsiPublishAssemblies", .description = "Publishing assembly information", .template_ = "Application Context:[1], Assembly Name:[2]" },
		{.action = "MsiUnpublishAssemblies", .description = "Unpublishing assembly information", .template_ = "Application Context:[1], Assembly Name:[2]" },
		{.action = "Rollback", .description = "Rolling back action:", .template_ = "[1]" },
		{.action = "RollbackCleanup", .description = "Removing backup files", .template_ = "File: [1]" },
		{.action = "UnmoveFiles", .description = "Removing moved files", .template_ = "File: [1], Directory: [9]" },
		{.action = "UnpublishProduct", .description = "Unpublishing product information" },
	};
}

void MSISequences::createTables(MSIDatabase* db)
{
	db->createTable(installUISequence);
	db->createTable(installExecuteSequence);
	db->createTable(adminUISequence);
	db->createTable(adminExecuteSequence);
	db->createTable(advtExecuteSequence);
}
